# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6b578c896a82f3171ff2c34418404b3665d78436

{
  "title": "Шкаф HOFF #3",
  "description": "Срочно",
  "status": "OPEN"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/26/
Content-Type: application/json
Authorization: Token 9d0819a96bb8f45c3002a29baa15494c438bd251

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2024-10-01
Content-Type: application/json

###

# удалить объявление
DELETE {{baseUrl}}/advertisements/25/
Content-Type: application/json
Authorization: Token 9d0819a96bb8f45c3002a29baa15494c438bd251