# Generated by Django 4.1.4 on 2022-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('image', models.CharField(max_length=200, verbose_name='Фотография')),
                ('release_date', models.DateField(verbose_name='Дата публикации')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие')),
            ],
        ),
    ]
